config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hens, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reservations, only: [:new, :create]
  end

  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hen.rb
class Hen < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true
  # validates :photo, presence: true
  validates :address, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :hen

  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :user, uniqueness: { scope: :hen }
  validates :start_date, uniqueness: { scope: :end_date }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hens, dependent: :destroy
  has_many :reservations, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader

  # before_create :set_default_avatar

  # def set_default_avatar
  #   default_url = "https://topgear.com.my/sites/default/files/default_images/avatar-default.png"
  #   if self.photo.present?
  #     self.photo = default_url
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end
end

app/controllers/hens_controller.rb
class HensController < ApplicationController
  before_action :set_hen, only: [:show, :edit, :update, :destroy]

  def index
    if Hen.geocoded.where("address ILIKE ?", "%#{params[:query]}%").length > 0
      @hens = Hen.geocoded.where("address ILIKE ?", "%#{params[:query]}%") # ("title ILIKE ?", "%#{params[:query]}%")
    else
      @hens = Hen.all
      flash.now[:notice] = "Pas de poules à l'adresse indiquée, vous êtes revenu à l'index !"
    end
    @markers = @hens.map do |hen|
      {
        lat: hen.latitude,
        lng: hen.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { hen: hen })
      }
    end
  end

  def show
    @markers = [lat: @hen.latitude, lng: @hen.longitude]
  end

  def new
    @hen = Hen.new
  end

  def create
    @hen = Hen.new(hen_params)
    @hen.user = current_user
    if @hen.save
      redirect_to hen_path(@hen)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @hen.update(hen_params)
      redirect_to hen_path(@hen)
    else
      render :edit
    end
  end

  def destroy
    @hen.destroy
  end

  private

  def set_hen
    @hen = Hen.find(params[:id])
  end

  def hen_params
    params.require(:hen).permit(:name, :address, :description, :eggs_per_day, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    redirect_to hens_path if current_user
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_hen
  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.hen = @hen
    @reservation.user = current_user
    dispo = true
    @hen.reservations.each do |resa|
      @start = resa.start_date
      @end = resa.end_date
      if @reservation.start_date.between?(@start, @end) || @reservation.end_date.between?(@start, @end)
        flash.now[:notice] = "#{@hen.name} n'est pas disponible à ces dates"
        dispo = false
      end
    end
    set_total_price
    if @reservation.save && dispo == true
      redirect_to dashboard_path
    else
      render '../views/reservations/new'
    end
  end
  #   set_total_price
  #   if @reservation.save
  #     redirect_to dashboard_path
  #   else
  #     render :new
  #   end
  # end

  def set_total_price
    @days = (@reservation.end_date - @reservation.start_date).to_i
    @reservation.total_price = @days * @reservation.hen.price_per_day
  end

  private

  def set_hen
    @hen = Hen.find(params[:hen_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hens/_info_window.html.erb
<h2><%= hen.name %></h2>
<p><%= hen.address %></p>
<p><%= hen.price_per_day %></p>

app/views/hens/edit.html.erb
<h2>Modifier ma poule</h2>
<%= simple_form_for(@hen) do |f| %>
<div class="row justify-content-center">
  <div class="col-12 col-lg-6 col-lg-4">
    <div class="form-inputs">
      <div class="form-group">
        <%= f.input :name %>
        <%= f.input :price_per_day %>
        <%= f.input :eggs_per_day %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      </div>
    </div>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit, class: "btn btn-secondary" %>
</div>
<% end %>
<%= link_to 'Revenir à mon dashboard', dashboard_path %>

app/views/hens/index.html.erb
<h2>Trouve ta poulette</h2>
<%= form_tag hens_path, method: :get, class:"d-flex" do %>
<%= text_field_tag :query,
params[:query],
class: "form-control-index",
placeholder: "Où picore votre poule ?"
%>
<%= submit_tag "Search", class: "btn btn-primary  search-button " %>
<% end %>
<div class="container-card">
  <div class="row row-index">
    <% @hens.each do |hen| %>
    <div class="col-12 col-md-6">
      <div class="card" >
        <!-- <img src=<%= hen.photo %> alt="Hen"> -->
        <%= link_to hen_path(hen), class:"card-title", style:"background-image: url( #{hen.photo} )" do %>
        <h4><%=hen.name%></h4>
        <% end %>
        <div class="card-description">
          <p>Ponte journalière: <%= hen.eggs_per_day %> oeufs/par jour</p>
          <p><%= hen.price_per_day %>€</p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    >
  </div>
</div>

app/views/hens/new.html.erb
<h2>Créez votre poule</h2>
<%= simple_form_for(@hen) do |f| %>
<div class="row justify-content-center">
  <div class="col-12 col-lg-6 col-lg-4">
    <div class="form-inputs">
      <div class="form-group">
        <%= f.input :name %>
        <%= f.input :price_per_day %>
        <%= f.input :eggs_per_day %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      </div>
    </div>
  </div>
</div>
<div class="form-actions">
<%= f.button :submit, class: "btn btn-secondary" %>
</div>
<% end %>
<%= link_to 'Revenir à mon dashboard', dashboard_path %>

app/views/hens/show.html.erb
<div class="container-fluid">
  <div class="d-flex align-items-center"> <!-- d-flex ==> display:flex -->
    <!-- 1ER BLOC -->
    <div class="hen_infos">
      <div class="hen_infos__identity d-flex align-items-center">
        <!-- ICONE -->
        <h4> <%= @hen.name %></h4>
      </div>
      <div class="hen_infos__identity d-flex align-items-center">
        <%= icon('fas', 'egg') %>
        <p>Ponte journalière : <%= @hen.eggs_per_day %></p>
      </div>
      <div class="hen_infos__identity d-flex align-items-center">
        <%= icon('fas', 'calendar-week') %>
        <p><%= @hen.address %> - <%= @hen.description %></p>
      </div>
      <div class="hen_infos__identity d-flex align-items-center">
        <%= icon('fas', 'user-alt') %>
        <p> Propriétaire : <%= @hen.user.username %> </p>
      </div>
    </div>
    <!-- 2EME BLOC -->
    <div class="hen_poule">
      <%= cl_image_tag @hen.photo, alt: "C'est la poule #{@hen.name}", width: "400" %>
      <div class="hen_infos__identity d-flex align-items-center">
        <%= icon('fas', 'dollar-sign') %>
        <p>Tarif journalier : <%= @hen.price_per_day %>€</p>
      </div>
      <% if current_user != @hen.user %>
        <%=link_to 'Je réserve ma poule', new_hen_reservation_path(@hen), class: 'btn btn-dark w-100' %>
      <% else %>
        <%=link_to 'Je modifie ma poule', edit_hen_path(@hen), class: 'btn btn-dark w-100' %>
      <% end %>
    </div>
    <!-- 3EME BLOC -->
    <div
    id="map"
    style="width: 40%;
    height: 500px; padding: 1em 1em 0em 1em;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <div>
    <%= link_to "Retourner à la liste des poules", hens_path, class: 'btn btn-outline-secondary'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Poulax</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="page"><%= yield %></div>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This page is made with <i class="fas fa-heart"></i> at Poulax
      </div>
    </div>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/92cd8d7d66.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h2>Tableau de bord</h2>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="hens_infos">
        <h3>Mon poulailler</h3>
        <% current_user.hens.each do |hen| %>
          <div class="hen_infos__identity">
            <%= link_to hen_path(hen), style:"background-image: url( #{hen.photo} )" do %>
              <h4><%=hen.name%></h4>
            <% end %>
            <%= link_to 'Modifier ma poule', edit_hen_path(hen), class: "btn btn-primary button-hen" %>
            <%= link_to 'Supprimer ma poule', hen_path(hen), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary button-hen" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="hens_infos">
        <h3>Détail des réservations</h3>
        <% current_user.reservations.each do |resa| %>
          <div class="hen_infos__identity">
            <!-- <p> Du<%= resa.start_date %> Au <%= resa.end_date %></p> -->
            <%= cl_image_tag resa.hen.photo, width: 100 %>
            <%= resa.hen.name %>
            <!-- <p>Prix total : <%= resa.total_price %> €</p> -->
          </div>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-center dashbord-buttons">
      <%= link_to "Ajouter une Poule", new_hen_path, class: 'btn btn-outline-secondary button-1' %>
      <%= link_to "Retourner à la liste des poules", hens_path, class: 'btn btn-outline-secondary button-2' %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row h-500">
    <div class="col-xs-12 col-md-6">
      <div class="banner-text">
        <h1>Elever des poules peut vous changer la vie</h1>
        <h2>"Découvrez pourquoi aller chercher ses oeufs, chaque jour, est un vrai plaisir"</h2>
        <a class="btn btn-primary btn-lg" href= "/hens">Découvrez Poulax </a>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class= "banner-img">


        <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">

          <div class="carousel-inner">
            <div class="carousel-item active" data-interval="5000">
              <p>"Nous sommes ravis d’avoir découvert Poulax !
                Nos enfants ont pu bénéficier des joies de la campagne avec Colette, notre poule de la semaine.
              Je recommande !" Claire</p>
            </div>
            <div class="carousel-item" data-interval="5000">
              <p>"Merci à Poulax pour ces délicieux petit-dej que nous avons pu prendre grâce à notre poule Corinne" Marc</p>
            </div>
            <div class="carousel-item" data-interval="5000">
              <p>"Juste génial ! Retrouver les plaisirs d'enfance et aller chercher ses oeufs frais, le bonheur, merci Poulax!" Thibaud</p>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<h2>Choisissez vos dates</h2>
<!-- <label for="start">Début</label>
<input type="date" name="trip-start" >
<label for="end">Fin</label>
<input type="date" name="trip-start" > -->
<%= simple_form_for ([@hen, @reservation]) do |f| %>
<div class="row justify-content-center">
  <div class="col-12 col-lg-6 col-lg-4">
    <div class="form-inputs">
      <div class="form-group">
        <%= f.input :start_date, html5: true %>
        <%= f.input :end_date, html5: true %>
      </div>
    </div>
  </div>
</div>
<div class="form-actions">
<%= f.button :submit, class: "btn btn-secondary" %>
</div>
<% end %>
<%= link_to 'Revenir aux détails de la poule', hen_path(@hen) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
<%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", hens_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.photo.present? %>
        <%= cl_image_tag current_user.photo, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= cl_image_tag "https://res.cloudinary.com/dljfsfpna/image/upload/v1575025976/avatar_sipc49.png", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>